Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/home/duckietown/scm/duckuments/mcdp/src/mcdp_utils_xml/__init__.py", line 6, in <module>
    from .note_errors_inline import *
  File "/home/duckietown/scm/duckuments/mcdp/src/mcdp_utils_xml/note_errors_inline.py", line 2, in <module>
    from mcdp import logger
  File "/home/duckietown/scm/duckuments/mcdp/src/mcdp/__init__.py", line 5, in <module>
    from .dependencies import *
  File "/home/duckietown/scm/duckuments/mcdp/src/mcdp/dependencies.py", line 19, in <module>
    import quickapp  # @UnusedImport
  File "/home/duckietown/scm/duckuments/deploy/local/lib/python2.7/site-packages/quickapp/__init__.py", line 17, in <module>
    from .quick_multi_app import *
  File "/home/duckietown/scm/duckuments/deploy/local/lib/python2.7/site-packages/quickapp/quick_multi_app.py", line 9, in <module>
    from reprep.utils import deprecated
  File "/home/duckietown/scm/duckuments/deploy/local/lib/python2.7/site-packages/reprep/__init__.py", line 12, in <module>
    from .mpl import *
  File "/home/duckietown/scm/duckuments/deploy/local/lib/python2.7/site-packages/reprep/mpl.py", line 35, in <module>
    try_load_matplotlib()
  File "/home/duckietown/scm/duckuments/deploy/local/lib/python2.7/site-packages/reprep/mpl.py", line 17, in try_load_matplotlib
    import matplotlib
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1133, in <module>
    rcParams = rc_params()
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 967, in rc_params
    fname = matplotlib_fname()
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 796, in matplotlib_fname
    configdir = _get_configdir()
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 649, in _get_configdir
    return _get_config_or_cache_dir(_get_xdg_config_dir())
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 626, in _get_config_or_cache_dir
    return _create_tmp_config_dir()
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 550, in _create_tmp_config_dir
    tempdir = tempfile.gettempdir()
  File "/usr/lib/python2.7/tempfile.py", line 275, in gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/lib/python2.7/tempfile.py", line 217, in _get_default_tempdir
    ("No usable temporary directory found in %s" % dirlist))
IOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/home/duckietown/scm/duckuments']
